[package]
name = "stone_os"
version = "0.1.0"
edition = "2024"
authors = ["Jesse van Gool"]

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


[[bin]]
name="stone_os"
test = false
bench = false

